worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;

    # Threat files with a unknown filetype as binary
    default_type application/octet-stream;
    client_max_body_size 21M;
    keepalive_timeout 65;

    # Enable gzip compression by default
    gzip on;
    gzip_proxied any;
    # Based on CloudFlare's recommended settings
    gzip_types text/richtext text/plain text/css text/x-script text/x-component text/x-java-source text/x-markdown application/javascript application/x-javascript text/javascript text/js image/x-icon image/vnd.microsoft.icon application/x-perl application/x-httpd-cgi text/xml application/xml application/rss+xml application/vnd.api+json application/x-protobuf application/json multipart/bag multipart/mixed application/xhtml+xml font/ttf font/otf font/x-woff image/svg+xml application/vnd.ms-fontobject application/ttf application/x-ttf application/otf application/x-otf application/truetype application/opentype application/x-opentype application/font-woff application/eot application/font application/font-sfnt application/wasm application/javascript-binast application/manifest+json application/ld+json application/graphql+json application/geo+json;
    gzip_vary on;
    gzip_disable "msie6";

    # map $http_x_forwarded_proto $fastcgi_param_https_variable {
    #     default '';
    #     https 'on';
    # }

    server {
        listen 8080;
        root /app/public;

        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            # fastcgi_param HTTPS on;
            fastcgi_index index.php;

            include fastcgi_params;
        }


        # allow access to the .well-known directory
        location ^~ /.well-known/ {
            allow all;
        }

        # Deny access to . files, for security
        location ~ /\. {
            log_not_found off;
            deny all;
        }
    }
}
